defaults:
  - foil: base
  - solver: base
  - plotting: web
  - _self_

alpha_start: 0.
alpha_end: 10.
alpha_step: .1

hydra:
  sweeper:
    params:
      foil.m: range(0.02,0.08,0.02)
      foil.t: range(0.1,0.2,0.05)
  sweep:
    dir: multirun/${hydra.job.name}
    subdir: ${hydra.job.override_dirname}/
  run:
    dir: outputs/${hydra.job.name}/${hydra.job.override_dirname}
  job:
    chdir: True
